# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=254, unique=True)),
                ('agencyAddress', models.CharField(blank=True, max_length=254)),
                ('agencyTelephone', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockIn', models.CharField(blank=True, max_length=98, null=True)),
                ('clockOut', models.CharField(blank=True, max_length=98, null=True)),
                ('hours', models.IntegerField(blank=True)),
                ('month', models.CharField(blank=True, max_length=98, null=True)),
                ('actDate', models.CharField(blank=True, max_length=98, null=True)),
                ('status', models.CharField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=254)),
                ('dateOp', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('reason', models.CharField(blank=True, max_length=254)),
                ('dateBonus', models.DateField(blank=True, null=True)),
                ('empCode', models.CharField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCat', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('reason', models.CharField(blank=True, max_length=254)),
                ('dateDeduction', models.DateField(blank=True, null=True)),
                ('empCode', models.CharField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=254)),
                ('dptSpecification', models.CharField(blank=True, max_length=254)),
                ('dptMinsalary', models.DecimalField(decimal_places=2, max_digits=25)),
                ('dptPaymentRaise', models.IntegerField(blank=True)),
                ('dpthourlySalary', models.DecimalField(decimal_places=2, max_digits=25)),
                ('doc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('reason', models.CharField(blank=True, max_length=254)),
                ('dateExp', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logOperation', models.CharField(blank=True, max_length=254)),
                ('dateO', models.DateField(blank=True, null=True)),
                ('logResult', models.CharField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=254)),
                ('quantity', models.IntegerField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25)),
                ('reason', models.CharField(blank=True, max_length=254)),
                ('dateOp', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('typeMenu', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNum', models.CharField(blank=True, max_length=254)),
                ('orderNumber', models.CharField(blank=True, max_length=254)),
                ('quantity', models.IntegerField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25)),
                ('status', models.CharField(blank=True, max_length=254)),
                ('dateOp', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePdt', models.CharField(blank=True, max_length=254)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=25)),
                ('quantity', models.IntegerField(blank=True)),
                ('minimum', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=254)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=254)),
                ('empCode', models.CharField(blank=True, max_length=254)),
                ('picture', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=254)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ceo'), (2, 'Admin'), (3, 'Branch Manager'), (4, 'Purchase Manager'), (5, 'Cashier'), (6, 'Avaris'), (7, 'Human Resource'), (8, 'Waitress')], null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencys', to='QuickServe.Agency')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25)),
                ('justification', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('dateOp', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(blank=True, max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=25)),
                ('salesDate', models.DateField(blank=True, null=True)),
                ('custmerSign', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('customer', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('stockType', models.CharField(blank=True, max_length=254)),
                ('dateStock', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Menu'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaris',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Product'),
        ),
        migrations.AddField(
            model_name='avaris',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
