# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Menu'),
        ),
    ]
