# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0002_auto_20170820_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nameCat',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='namePdt',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='empCode',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ceo'), (2, 'Admin'), (3, 'Branch Manager'), (4, 'Purchase Manager'), (5, 'Cashier'), (6, 'Avaris'), (7, 'Human Resource'), (8, 'Operation'), (9, 'Waitress')], null=True),
        ),
    ]
