# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0003_auto_20170821_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='justification',
        ),
    ]
