# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0005_purchases_justification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='justification',
        ),
    ]
