# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0006_remove_purchases_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dateStock',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
