# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0007_auto_20170826_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NumbersOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='dateOp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
