# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuickServe', '0008_auto_20170826_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNum', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(blank=True, max_length=254)),
                ('dateOp', models.DateTimeField(blank=True, null=True)),
                ('orderNumber', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='tableNum',
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
