# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0009_auto_20170826_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tabs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Tabs'),
        ),
    ]
