# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0010_orders_tabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tabs',
        ),
    ]
