# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0011_remove_orders_tabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=254, null=True)),
                ('dateOp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
