# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0012_printmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='custmerSign',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoiceNumber',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='salesDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
