# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0013_auto_20170828_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
