# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0014_auto_20170828_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
