# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0015_auto_20170830_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clockinHr',
            field=models.CharField(blank=True, max_length=98, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clockoutHr',
            field=models.CharField(blank=True, max_length=98, null=True),
        ),
    ]
