# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0016_auto_20170830_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='tableNum',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
