# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0018_auto_20171005_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderNumber',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuickServe.Product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
