# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0022_auto_20171005_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
