# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0023_auto_20171005_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabs',
            name='total',
        ),
    ]
