# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0024_remove_tabs_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='custmerSign',
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
