# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0026_auto_20171015_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='printmsg',
            name='totalSale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='totalSale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
