# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServe', '0027_auto_20171017_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='totalSale',
        ),
    ]
